#!/usr/bin/env python3
"""recover_2450.py — replace the bogus third-party AQA A-level Physics 2450
legacy PDF with the genuine spec from the Internet Archive, then update the CSV.
JSON is regenerated by re-running extract_syllabus.py over the tree afterwards."""
import csv, io, os
from datetime import date
import fitz
import lib_fetch

ROOT = os.path.dirname(os.path.abspath(__file__))
SYLL = os.path.join(ROOT, "Syllabuses")
CSV_PATH = os.path.join(ROOT, "Syllabus_Master_Index.csv")
TODAY = date.today().isoformat()

FPATH = os.path.join(SYLL, "AQA", "A_Level", "Physics", "2450_2005_to_2016",
                     "AQA_ALEVEL_Physics_2450_2005_to_2016_LEGACY.pdf")

CANDIDATES = [
    ("20131101201052", "http://filestore.aqa.org.uk:80/subjects/specifications/alevel/AQA-2450-W-SP-14.PDF"),
    ("20130418120300", "http://filestore.aqa.org.uk:80/subjects/AQA-2450-W-SP.PDF"),
    ("20080905190905", "http://www.aqa.org.uk/qual/gce/pdf/AQA-2450-W-SP-10.PDF"),
]


def is_real_spec(data):
    try:
        doc = fitz.open(stream=data, filetype="pdf")
    except Exception:
        return False
    txt = "\n".join(doc[i].get_text("text") for i in range(min(6, doc.page_count))).lower()
    doc.close()
    has_sc = "subject content" in txt
    looks_paper = ("mark scheme" in txt or "question paper" in txt) and "specification" not in txt
    return has_sc and not looks_paper


def main():
    data, src = None, ""
    for ts, orig in CANDIDATES:
        url = f"https://web.archive.org/web/{ts}id_/{orig}"
        d = lib_fetch.fetch_pdf(url)
        if d and len(d) > 20000 and is_real_spec(d):
            data, src = d, url
            print(f"valid spec from {orig} ({len(d)//1024} KB)")
            break
        print(f"  rejected: {orig} ({'no data' if not d else str(len(d)//1024)+'KB, not a spec'})")
    if not data:
        print("No genuine 2450 spec recovered."); return

    open(FPATH, "wb").write(data)
    print("replaced", os.path.relpath(FPATH, ROOT))

    rows = list(csv.DictReader(open(CSV_PATH, encoding="utf-8")))
    for r in rows:
        if r["Spec_Code"] == "2450":
            r["Source_URL"] = src
            r["Notes"] = f"OK ({len(data)//1024} KB) [Wayback; genuine AQA-2450-W-SP-14 spec, replaced bad third-party PDF]"
    tmp = CSV_PATH + ".tmp"
    import naming
    with open(tmp, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=naming.CSV_HEADER); w.writeheader(); w.writerows(rows)
    os.replace(tmp, CSV_PATH)
    print("CSV row for 2450 updated")


if __name__ == "__main__":
    main()
